name: DOCTOR_MANAGEMENT_BACKEND

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: leafy-flash-441005-g2
  REGION: asia-south1
  REPOSITORY: doctormanagement
  IMAGE_NAME: backend
  CLUSTER_NAME: cluster-1
  CLUSTER_ZONE: us-central1-c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to Google Cloud
      - name: Set up GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 3️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 4️⃣ Build & push image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG

      # 5️⃣ Install GKE Auth Plugin
      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # 6️⃣ Connect to GKE
      - name: Get Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}

      # 7️⃣ Update image in k8s yaml
      - name: Replace Image in Deployment
        run: |
          IMAGE_TAG=${{ github.sha }}
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG|g" k8s/deployment.yaml

      # 8️⃣ Deploy to GKE
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
